Tests automated, secure connection & retry methods added
siddhi-io/siddhi-store-mongodb pull request #6
Opened 2017-07-04 13:54 UTC by Niveathika92

1. Tests automated - Normal as well as secure connections
2. Fix for secure connection - Including trust store and key store
3. Connect, Close and destroy method implementation(Siddhi-M12)

2017-07-04 18:58 UTC, tishan89 requested changes

2017-07-04 18:58 UTC, tishan89 commented on component/src/main/java/org/wso2/extension/siddhi/store/mongodb/MongoDBEventTable.java
> +            throw new MongoTableException("Annotation 'Store' contains illegal value for " +
Why are we throwing this runtime exception to Siddhi? If you want initialization to fail shall we throw SiddhiAppCreationException? WDYT?

2017-07-04 18:58 UTC, tishan89 commented on component/src/main/java/org/wso2/extension/siddhi/store/mongodb/MongoDBEventTable.java
> +        if (!this.initialCollectionTest) {
format the code

2017-07-05 04:24 UTC, Niveathika92 commented on component/src/main/java/org/wso2/extension/siddhi/store/mongodb/MongoDBEventTable.java
> +            throw new MongoTableException("Annotation 'Store' contains illegal value for " +
I've changed the initializing exceptions to SiddhiAppCreationException in d1c214c

2017-07-05 04:24 UTC, Niveathika92 commented on component/src/main/java/org/wso2/extension/siddhi/store/mongodb/MongoDBEventTable.java
> +        if (!this.initialCollectionTest) {
Addressed the issues in d1c214c

2017-07-05 04:54 UTC, merged